// Sidebar sinh tự động từ cây docs/. Nhãn thư mục lấy từ _category_.json,
// thứ tự lấy từ "position" trong file đó.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
